version: "3.9"
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tech-tank
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tech-tank-test-network

networks:
  tech-tank-test-network:
    driver: bridge

volumes:
  postgres-data:

